name: APIM ENV CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Delete Gateway dependent file
        - rm src/main/java/com.axway.ExternalConfigLoader.java
      - name: Build with Maven
        run: mvn -Dtest test