name: APIM ENV CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn verify
      - name: jacoco-badge-generator
        uses: cicirello/jacoco-badge-generator@v2.5.0
